# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-10 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20180210_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='iss',
            name='resolve',
            field=models.BooleanField(default='False'),
        ),
    ]
