# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empinf', '0002_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.CharField(default='unassigned', max_length=264),
        ),
        migrations.AddField(
            model_name='employee',
            name='issues_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emid',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
